- webapp/components/ErrorBoundary.jsx
- webapp/errors.jsx
- webapp/pages/App.css
- webapp/pages/App.jsx
- webapp/pages/RepositoryDetails.jsx
Add two error states for the highest level route:
- 404/not found
- generic unhandled error
> feat: Add basic error boundaries

- tests/zeus/api/resources/test_build_styleviolations.py
- zeus/api/__init__.py
- zeus/api/resources/build_styleviolations.py
- zeus/api/schemas/fields/severity.py
- zeus/api/schemas/styleviolation.py
- zeus/cli/mocks.py
- zeus/factories/styleviolation.py
- zeus/factories/testcase.py
This adds various components needed to support the StyleViolation schema, including the
API schema and factory components.
> feat: Add build style violations endpoint

- webapp/components/BuildDetailsBase.jsx
- webapp/components/BuildOverviewBase.jsx
- webapp/components/StyleViolationList.jsx
- webapp/pages/BuildStyleViolationList.jsx
- webapp/routes.jsx
- zeus/api/schemas/stats.py
- zeus/tasks/aggregate_job_stats.py
> feat: Add draft style violations UI

- .babelrc
- config/webpack.config.js
- package.json
- templates/index.html
- webapp/components/PageLoading.jsx
- webapp/routes.jsx
- yarn.lock
- zeus/config.py
- Support code splitting within webpack configuration
- Remove service worker cache plugin (unused)
- Add hashing to asset generation
- Utilize react-loadable for async settings components (WIP)
- Add vendor bundle with large chunk of third party libs
> feat: Add code splitting and chunk hashing

- kubernetes/zeus/.gitignore
- kubernetes/zeus/Chart.yaml
- kubernetes/zeus/README.md
- kubernetes/zeus/config
- kubernetes/zeus/deploy
- kubernetes/zeus/kube-lego/configmap.yaml
- kubernetes/zeus/kube-lego/deployment.yaml
- kubernetes/zeus/kube-lego/namespace.yaml
- kubernetes/zeus/requirements.lock
- kubernetes/zeus/requirements.yaml
- kubernetes/zeus/values.yaml
- kubernetes/zeus/zeus/nfs-pv.yaml
- kubernetes/zeus/zeus/nfs-pvc.yaml
- kubernetes/zeus/zeus/nfs-server-pvc.yaml
- kubernetes/zeus/zeus/nfs-server-rc.yaml
- kubernetes/zeus/zeus/nfs-server-service.yaml
- kubernetes/zeus/zeus/pubsub-deployment.yaml
- kubernetes/zeus/zeus/pubsub-service.yaml
- kubernetes/zeus/zeus/redis-master-deployment.yaml
- kubernetes/zeus/zeus/redis-master-service.yaml
- kubernetes/zeus/zeus/repo-sc.yaml
- kubernetes/zeus/zeus/standard-sc.yaml
- kubernetes/zeus/zeus/web-deployment.yaml
- kubernetes/zeus/zeus/web-ingress.yaml
- kubernetes/zeus/zeus/web-service.yaml
- kubernetes/zeus/zeus/worker-deployment.yaml
Please forgive us world, we have no idea what we're doing here.
> feat: Add gcp/kubernetes configs

- requirements-base.txt
- tests/zeus/api/resources/test_hook_details.py
- tests/zeus/api/resources/test_repository_hooks.py
- tests/zeus/providers/travis/test_base.py
- tests/zeus/providers/travis/test_webhook.py
- zeus/api/resources/hook_details.py
- zeus/api/schemas/hook.py
- zeus/factories/hook.py
- zeus/migrations/f78a2be4ddf9_rename_hook_data.py
- zeus/models/hook.py
- zeus/providers/base.py
- zeus/providers/travis/__init__.py
- zeus/providers/travis/base.py
- zeus/providers/travis/webhook.py
- zeus/testutils/fixtures.py
Add a ``Provider`` class which can define hook configuration for a provider using JSON schema. Implement a TravisProvider which handles the ``domain`` configuration.
Refs GH-87
> feat: Add config to build providers

- tests/zeus/api/resources/test_github_repositories.py
- zeus/api/resources/github_repositories.py
> fix: Grant permissions when repo is enabled

- tests/zeus/api/resources/test_repository_hooks.py
- zeus/api/schemas/hook.py
- zeus/providers/custom.py
> fix(hooks): Support "custom" hook provider

- webapp/pages/RevisionStyleViolationList.jsx
- webapp/routes.jsx
- zeus/api/__init__.py
- zeus/api/resources/revision_bundlestats.py
- zeus/api/resources/revision_styleviolations.py
Should fix https://sentry.io/sentry/zeus/issues/418137327/?environment=production
> fix: Add missing API endpoints for revisions

- templates/index.html
- webapp/components/Footer.jsx
- webapp/components/Layout.jsx
- webapp/components/__tests__/__snapshots__/BuildList.spec.jsx.snap
- webapp/components/__tests__/__snapshots__/RevisionList.spec.jsx.snap
> feat: Add footer with build/github

- tests/zeus/api/resources/test_install_index.py
- tests/zeus/utils/test_metrics.py
- zeus/api/resources/install_index.py
- zeus/auth.py
- zeus/config.py
- zeus/migrations/e2f926a2b0fe_add_user_date_active.py
- zeus/models/user.py
- zeus/utils/metrics.py
- Track 'active' users with new date_active field
- Update all stats to be 'active' within 24h/30d
- Add generic traffic hit counting to local process stats
- Add process id
- Add uptime
- Add connections gauge
> feat: Various improvements to statistics

- zeus/api/utils/upserts.py
- zeus/utils/redis.py
...as a temporary measure. 
Also: rewrite redis locking code to use the built-in `redis.lock`.
> fix: Increase timeout for build locks

- kubernetes/zeus/config
- kubernetes/zeus/deploy
A few minor changes to make it easier to deploy Zeus via Freight.
> deploy: Use Freight

- poetry.lock
- pyproject.toml
> ref: Update Python SDK to 0.10.1

- webapp/components/BuildCoverage.jsx
- webapp/components/__tests__/BuildCoverage.spec.jsx
- webapp/components/__tests__/__snapshots__/BuildCoverage.spec.jsx.snap
- webapp/pages/RevisionCoverage.jsx
- zeus/api/__init__.py
- zeus/api/resources/repository_file_coverage_tree.py
- zeus/api/resources/revision_file_coverage_tree.py
Additionally this improves the coverage view to include diff statistics.
> feat: Unify revision and build coverage views

- zeus/tasks/cleanup_artifacts.py
- zeus/tasks/cleanup_builds.py
> ref: Additional logging for cleanup tasks

- zeus/config.py
- zeus/tasks/cleanup_builds.py
> ref: Split up cleanup celery tasks

- zeus/tasks/resolve_ref.py
- zeus/tasks/sync_repo.py
- zeus/utils/repos.py
> feat: Disable repos when ref fetches fail

- zeus/tasks/cleanup_builds.py
> feat: Cleanup errored unfinished builds

- poetry.lock
- pyproject.toml
> ref: Update deps to fix setuptools req

- zeus/utils/revisions.py
> ref: Remove lock on identify_revision

- zeus/tasks/sync_repo.py
> fix: Bad timedelta reference

- zeus/cli/repos.py
> feat: Expose --force/--no-force option in repos sync

- webapp/pages/RepositoryHookDetails.jsx
> fix: Correct handling configured value for Travis domain

- zeus/vcs/git.py
> feat: Limit depth of repos to avoid large memory consumption

- zeus/vcs/git.py
> fix: Correct raise statement placement

- kubernetes/zeus/zeus/worker-deployment.yaml
> ref: Increase memory limits for workers

- zeus/migrations/16414a5b4ed9_backfill_authors.py
> fix: Handle missing authors

- bors.toml
> build: Delete merged branches via bors

- zeus/migrations/16414a5b4ed9_backfill_authors.py
> ref: Remove wrong/expensive loop on migration

- kubernetes/zeus/zeus/pubsub-deployment.yaml
- kubernetes/zeus/zeus/web-deployment.yaml
- kubernetes/zeus/zeus/worker-deployment.yaml
> ref: Tweak resources to better suit production needs

- zeus/tasks/cleanup_builds.py
This reverts commit 1b7a634472a9a9d536582018cdc53c9b4c830ef1.
bors r+
> Revert "ref: Run cleanup subtasks in savepoints"

- kubernetes/zeus/zeus/worker.yaml
- poetry.lock
- pyproject.toml
> Fix various build components

- zeus/vcs/backends/base.py
> Fix  path to ssh-connect

- kubernetes/zeus/zeus/postgres.yaml
- zeus/vcs/db.py
> Switch pgbouncer to session pool

- zeus/vcs/db.py
> yet another attempt at fixing pgbouncer

- kubernetes/zeus/zeus/postgres.yaml
- zeus/vcs/db.py
> Remove code we shouldnt need

- zeus/vcs/server.py
> Correct lru cache key

- zeus/utils/revisions.py
> Fix invalid next() call on api result

- tests/zeus/vcs/conftest.py
- tests/zeus/vcs/test_client.py
- zeus/exceptions.py
- zeus/testutils/fixtures.py
- zeus/vcs/api.py
- zeus/vcs/backends/git.py
- zeus/vcs/client.py
> Repropagate UnknownRevision errors

- tests/zeus/api/test_authentication.py
- tests/zeus/utils/test_auth.py
- zeus/api/authentication.py
- zeus/api/resources/base.py
- zeus/auth.py
- zeus/vcs/api.py
> Improve token handling to include sentry context

- zeus/tasks/process_artifact.py
> Ensure countdown is properly overwritten

- tests/zeus/api/test_authentication.py
- tests/zeus/utils/test_auth.py
- tests/zeus/vcs/test_api.py
- zeus/auth.py
- zeus/pubsub/server.py
- zeus/vcs/api.py
- zeus/vcs/client.py
bors r+
need to get test coverage for this path
> Fix explicit passing of access to tenants

- kubernetes/zeus/zeus/vcs-server.yaml
> Add missing labels to vcs-server statefulset

- zeus/vcs/server.py
Fixes ZEUS-1RMD
Fixes ZEUS-1RME
> Disable asyncpg statement cache

- webapp/index.jsx
> Tag browser as web-frontend role

- zeus/vcs/api.py
> Fix UUID str formatting for Sentry

- zeus/vcs/backends/base.py
> Always update repo if suggested

- zeus/vcs/backends/base.py
> Completely remove unused updated flag

- kubernetes/zeus/zeus/vcs-server.yaml
> Increase vcs-server disks to 5tb

- .envrc
- poetry.lock
- zeus/cli/shell.py
- Switch to start_ipython (fixes async, uses defaults)
- Load .env
bors r+
> Fix various dev env concerns (iPython, .env)

- zeus/vcs/backends/base.py
- zeus/vcs/backends/git.py
> Minor vcs cleanup

- zeus/vcs/api.py
> Force execution of iterator to catch unknown revisions

- tests/zeus/vcs/test_api.py
> Add test coverage for update-on-failure scenario

- zeus/pubsub/server.py
> Dont capture CancelledError

- webapp/pages/RepositoryDetails.jsx
- webapp/pages/__tests__/__snapshots__/RepositoryDetails.spec.jsx.snap
> Add missing footer on several pages

- tests/zeus/api/resources/test_revision_failures.py
- webapp/components/AggregateFailureList.jsx
- webapp/components/BuildOverviewBase.jsx
- zeus/api/__init__.py
- zeus/api/resources/revision_failures.py
- zeus/cli/mocks.py
> feat: Expose build failure reasons in UI

- config/jest/testStubs.js
- tests/zeus/api/resources/test_build_details.py
- tests/zeus/api/resources/test_build_index.py
- tests/zeus/api/resources/test_change_request_index.py
- webapp/components/BuildCoverage.jsx
- webapp/components/BuildListItem.jsx
- webapp/components/ObjectAuthor.jsx
- webapp/components/ResultGrid.jsx
- webapp/components/__tests__/ObjectAuthor.spec.jsx
- webapp/components/__tests__/__snapshots__/BuildCoverage.spec.jsx.snap
- webapp/components/__tests__/__snapshots__/BuildList.spec.jsx.snap
- webapp/components/__tests__/__snapshots__/CoverageSummary.spec.jsx.snap
- webapp/components/__tests__/__snapshots__/ObjectAuthor.spec.jsx.snap
- webapp/components/__tests__/__snapshots__/RevisionList.spec.jsx.snap
- webapp/pages/Dashboard.jsx
- webapp/pages/RepositoryOverview.jsx
- webapp/pages/UserBuildList.jsx
- webapp/pages/__tests__/__snapshots__/RepositoryOverview.spec.jsx.snap
- zeus/api/resources/build_index.py
- zeus/api/resources/change_request_index.py
- zeus/api/resources/repository_builds.py
- zeus/api/resources/repository_revisions.py
- zeus/api/resources/revision_details.py
- zeus/api/schemas/build.py
- zeus/api/schemas/repository.py
- zeus/api/schemas/revision.py
- zeus/factories/build.py
- zeus/factories/revision.py
- zeus/utils/builds.py
- Remove Build.author and Revision.author from API schemas
- Remove Build.author and Revision.author from API queries
- Update ObjectAuthor to render multiple authors
bors r+
> fix: Remove singular authors and migrate remaining code

- kubernetes/zeus/zeus/web.yaml
> Increase web nodes; decrease resource allocation

- tests/zeus/vcs/test_utils.py
- zeus/vcs/utils.py
> fix: Correct author name/email mixup

- zeus/migrations/54bbb66a65a6_fix_bad_authors.py
> fix: Correct invalid author rows

- zeus/api/schemas/build.py
- zeus/api/schemas/change_request.py
- zeus/factories/build.py
- zeus/factories/change_request.py
- zeus/factories/revision.py
- zeus/tasks/resolve_ref.py
> fix: Set authors rather than appending

- zeus/migrations/54bbb66a65a6_fix_bad_authors.py
> fix: Handle update when duplicate rows exist

- bin/docker-entrypoint
> fix: Remove auto db upgrade from docker commands

- zeus/migrations/54bbb66a65a6_fix_bad_authors.py
> fix: Correct clause on author migration

- poetry.lock
- zeus/utils/sentry.py
- zeus/vcs/backends/git.py
Add various spans for different git commands, all prefixed with 'vcs.'.
> ref: Improve span collection in vcs backend

- setup.cfg
- zeus/api/schemas/testcase.py
- zeus/auth.py
- zeus/config.py
- zeus/db/types/enum.py
- zeus/db/utils.py
- zeus/exceptions.py
- zeus/models/hook.py
- zeus/notifications/email.py
- zeus/storage/mock.py
- zeus/utils/builds.py
- zeus/utils/http.py
- zeus/utils/redis.py
- zeus/vcs/backends/git.py
- zeus/vcs/client.py
- zeus/vcs/providers/github.py
> ref: Various fixes and type annotations for mypy

- zeus/vcs/api.py
> ref: Log only uncaught errors in vcs api calls

- cloudbuild.yaml
> ref: Extend build timeout to 20m

- cloudbuild.yaml
> ref: Brute force build times with more options

- zeus/api/schemas/failurereason.py
> fix: NoneType is unsortable on build failures

- zeus/tasks/resolve_ref.py
> fix: Handle existing FailureReason row

- tests/zeus/tasks/test_resolve_ref.py
- tests/zeus/utils/test_revisions.py
- tests/zeus/vcs/test_api.py
- zeus/testutils/pytest.py
- zeus/utils/revisions.py
- zeus/vcs/api.py
- zeus/vcs/client.py
- zeus/vcs/server.py
This adds a new 'resolve' endpoint to VCS server and waits for the revision to be synced with the database.
bors r+
> feat: Move resolution to a synchronous endpoint

- zeus/tasks/resolve_ref.py
> ref: Improve lock behavior on resolution tasks

- zeus/api/resources/build_diff.py
- zeus/api/resources/revision_diff.py
> fix: Dont hard error when revision is not yet identified

- tests/zeus/tasks/test_resolve_ref.py
- zeus/tasks/aggregate_job_stats.py
> ref: Improve behavior of jobless failures

- tests/zeus/tasks/test_cleanup_builds.py
- webapp/components/AggregateFailureList.jsx
- zeus/models/failurereason.py
- zeus/tasks/aggregate_job_stats.py
- zeus/tasks/cleanup_builds.py
- Add internal_error and timeout reasons for job errors
- Add some consistency on setting date_finished
bors r+
> ref: Clean up aggregation and failure scenario handling

- zeus/tasks/resolve_ref.py
> ref: Log unresolvable ref errors

- tests/zeus/api/resources/test_job_details.py
- zeus/api/resources/job_details.py
> fix: Set job.date_updated on every PUT (not just POST)

- tests/zeus/tasks/test_cleanup_builds.py
- zeus/tasks/cleanup_builds.py
Also improve cleanup_jobs query pattern.
bors r+
> fix: Correct bad condition for cleanup_builds

- zeus/api/resources/build_details.py
> ref: Disable select for update on build mutation

- zeus/config.py
> feat: Support configuring rabbitmq directly from env

- zeus/config.py
> fix: Correct rabbitmq username from env

- .freight.yaml
- kubernetes/zeus/app-crd.yaml
- kubernetes/zeus/generate-rabbitmq-manifest
- kubernetes/zeus/rabbitmq-1_manifest.yaml
- kubernetes/zeus/rabbitmq-1_rbac.yaml
- kubernetes/zeus/requirements.lock
- kubernetes/zeus/requirements.yaml
- kubernetes/zeus/zeus/pubsub.yaml
- kubernetes/zeus/zeus/vcs-server.yaml
- kubernetes/zeus/zeus/web.yaml
- kubernetes/zeus/zeus/worker.yaml
> feat: Add new rabbitmq module (with stackdriver support)

- tests/zeus/providers/travis/test_webhook.py
- tests/zeus/tasks/test_process_travis_webhook.py
- zeus/providers/travis/webhook.py
- zeus/testutils/fixtures.py
> ref: Improve travis webhook logging for valid payloads

- tests/zeus/api/resources/test_build_index.py
- zeus/api/resources/build_index.py
- zeus/factories/failurereason.py
> feat: Add status, result, and failure_reason to build search API

- zeus/tasks/process_artifact.py
- zeus/vcs/client.py
> fix: Correct bad task names

- zeus/tasks/process_artifact.py
> fix: Improve artifact delay when pending revision resolution

- zeus/cli/repos.py
> feat: Add `repos get` cli

- tests/zeus/vcs/test_server.py
- tests/zeus/vcs/test_utils.py
- zeus/constants.py
- zeus/vcs/backends/base.py
- zeus/vcs/backends/git.py
- zeus/vcs/server.py
- zeus/vcs/utils.py
> feat: Add automatic cleanup to repositories

- zeus/exceptions.py
- zeus/vcs/backends/git.py
> ref: Capture and rethrow upstream host error

- zeus/tasks/process_artifact.py
- zeus/utils/celery.py
> fix: Pass countdown via apply_async

- zeus/utils/revisions.py
- zeus/vcs/client.py
> ref: Add 10 second timeout on ref resolve

- zeus/vcs/backends/git.py
> fix: Only run cleanup when repo exists

- zeus/tasks/cleanup_builds.py
> ref: Improve logging in cleanup_builds

- zeus/vcs/api.py
> ref: Add logging for resolution retry

- bin/ssh-connect
- zeus/config.py
This also disables logging for ssh-connect.
bors r+
> fix: Dont log to stdout (stderr is default)

- zeus/vcs/server.py
> ref: Use create_task per Python recommendations

- zeus/cli/mocks.py
> fix: Correct mocks for async calls

- zeus/db/utils.py
> fix: Correct behavior for try_create on duplicate keys

- webapp/components/AggregateTestList.jsx
- webapp/components/RepositoryHeader.jsx
- webapp/components/TestChart.jsx
- webapp/pages/RepositoryReportsLayout.jsx
- webapp/pages/RepositoryTests.jsx
- webapp/pages/__tests__/__snapshots__/RepositoryDetails.spec.jsx.snap
- webapp/routes.jsx
Move Coverage, Tests, and Stats into Reports location.
bors r+
> ref: Consolidate analytics-type features into new Reports section

- tests/zeus/api/resources/test_repository_tests.py
- webapp/pages/RepositoryTestList.jsx
- webapp/pages/RepositoryTests.jsx
- webapp/routes.jsx
- zeus/api/resources/repository_tests.py
- zeus/api/schemas/testcase.py
> feat: Improve data exposed with tests

- kubernetes/zeus/connect-to-postgres
> feat: Add helper for connecting to postgres instance

- zeus/api/resources/repository_tests.py
> ref: Limit number of jobs for tset results to 10k

- zeus/api/resources/repository_tests.py
> fix: Jobs should be 10k, not 1k

- zeus/tasks/cleanup_pending_artifacts.py
> ref: Improve logging for cleanup_pending_artifacts

- zeus/tasks/process_artifact.py
> ref: Improve artifact in-progress processing and logging

- tests/zeus/api/resources/test_job_artifacts.py
- tests/zeus/tasks/test_cleanup_artifacts.py
- zeus/tasks/cleanup_artifacts.py
> fix: Dont clean up artifacts which arent queued

- zeus/tasks/cleanup_artifacts.py
> Lower log level of normmal expiration to info

- bors.toml
> Move to squash merge for bors

- poetry.lock
- pyproject.toml
- zeus/config.py
This turns on auto session tracking for zeus.
> feat: turn on auto session tracking

- zeus/artifacts/coverage.py
> Improve coverage instrumentation with Sentry

- tests/zeus/tasks/test_process_pending_artifact.py
- zeus/tasks/process_pending_artifact.py
> fix: Wipe PendingArtifacts immediately (and preserve files)
