tests/zeus/web/test_auth_github.py
zeus/web/__init__.py

Without `public_repo`, Zeus cannot access the "keys" resource which is
needed to add the deploy key on repo activation.
This went partially unnoticed, since we're usually always working with
elevated permissions to access private repositories. The `repo` permission
also includes access to settings of public repositories.
In addition to this, a user also needs admin access to the repository.
This is covered by #52. Together, they should fix
[ZEUS-2X](https://sentry.io/sentry/zeus/issues/366310285/).

fix(github): Add public_repo to default GitHub permissions

---

tests/zeus/api/resources/test_github_repositories.py
tests/zeus/web/test_auth_github.py
webapp/components/Button.jsx
webapp/pages/GitHubRepositoryList.jsx
zeus/api/resources/github_repositories.py
zeus/api/schemas/repository.py
zeus/vcs/providers/github.py

Zeus requires admin privileges on a repository to add deploy keys. If the user
does not have these, the server currently errors with 500. This is caused by
a 404 on the GitHub resource due to insufficient permissions.
This PR adds a check for admin privileges on each repository. In the UI all
buttons are disabled where admin privileges are missing. Also, the server
now fails more gracefully with an error message.
**NOTE:** The repo cache will not contain the flag. Please clear the cache
on deployment (key: `gh:2:repos:*`).
This should also "fix" [ZEUS-2X](https://sentry.io/sentry/zeus/issues/366310285/)

fix: Only allow to enable repositories with admin privileges

---

Dockerfile
Makefile

This PR replaces the version of werkzeug required by flask with a commit that includes a fix for chunked transfer encoding. More information on this fix can be found at pallets/werkzeug#1198
It seems that the next release of werkzeug including this fix will not happen within the next month.
Chunked transfer encoding is required by the current version of `zeus-cli` to upload build artifacts.

build: Use werkzeug master instead of pip latest

---

package.json
requirements-base.txt
tests/zeus/api/resources/test_build_tests.py
webapp/components/AggregateTestList.jsx
webapp/components/ObjectDuration.jsx
webapp/pages/BuildTestList.jsx
webapp/pages/Dashboard.jsx
yarn.lock
zeus/api/resources/build_tests.py
zeus/api/resources/job_tests.py
zeus/api/resources/test_details.py
zeus/api/schemas/testcase.py

This makes a subtle change to the test list which will improve visibility into matrix builds which run the same test suite under multiple parameters (branching).
It uses aggregate entries with 'runs', and an aggregate result as well as 99th percentile duration. Expanding will expand all test runs within it, though the design isn't ideal here.

feat: Show aggregate test results on build details

---

tests/fixtures/sample-gotest.json
tests/zeus/artifacts/test_gotest.py
zeus/artifacts/__init__.py
zeus/artifacts/gotest.py
zeus/testutils/fixtures.py

The upcoming release of go1.10 includes machine parseable test output.

feat: Add support for go test -json output

---

tests/zeus/api/resources/test_github_repositories.py
tests/zeus/api/resources/test_repository_details.py
tests/zeus/api/resources/test_repository_index.py
webapp/components/RepositoryHeader.jsx
webapp/pages/GitHubRepositoryList.jsx
zeus/api/resources/github_repositories.py
zeus/api/schemas/repository.py
zeus/constants.py

This corrects issues where sometimes the permissions returned are not enums or they cannot easily be translated to a name.

fix: Use a map to track and utilize permissions in UI/API

---

tests/zeus/api/resources/test_user_builds.py
tests/zeus/api/schemas/test_testcase.py
zeus/api/resources/build_tests.py
zeus/api/schemas/testcase.py
zeus/factories/build.py
zeus/factories/revision.py
zeus/factories/source.py

While this should be fairly accurate, it isn't going to be perfect. Right now if a build is created as part of a change request (e.g. in a branch), and it coincidentally has a failing test which is the same as your branch, we'd likely point to it as the origin.

feat: Add failure origin to aggregate test cases

---

tests/zeus/utils/test_builds.py
zeus/utils/builds.py

This should fix
https://sentry.io/sentry/zeus/issues/611142817/?environment=production
https://sentry.io/sentry/zeus/issues/622534124/?environment=production

fix: Start/finish time comparison in case of multiple providers

---

webapp/pages/RepositoryHookDetails.jsx

This breaks sentry-cli builds currently, and we'll need it in other repos soon, too.

feat: Add a hook setting for travis domains

---

tests/fixtures/travis-build-commit.json
tests/fixtures/travis-build-pull-request.json
tests/zeus/api/resources/test_hook_details.py
tests/zeus/providers/travis/test_base.py
tests/zeus/providers/travis/test_webhook.py
tests/zeus/web/hooks/test_build_hook.py
tests/zeus/web/hooks/test_job_artifacts_hook.py
tests/zeus/web/hooks/test_job_hook.py
webapp/pages/RepositoryHookDetails.jsx
webapp/pages/RepositoryHooks.jsx
zeus/api/schemas/hook.py
zeus/api/utils/upserts.py
zeus/models/hook.py
zeus/providers/__init__.py
zeus/providers/base.py
zeus/providers/custom.py
zeus/providers/travis/base.py
zeus/testutils/fixtures.py
zeus/web/hooks/job.py
zeus/web/hooks/job_artifacts.py

This will make 'custom' hooks require a name, with the migration path being to fall back to 'custom' as the name for now.

feat: Use unique provider names for constraints

---

zeus/artifacts/webpack.py

The `assetByChunkName` key of the stats file can include non js assets like `static/css/main.900e26e0.css` and `static/css/main.900e26e0.css.map`. The problem in the existing logic is that we expect the `assets` key to have the same items as `assetByChunkName`, which is not the case for non-js assets.
This change skips assets in the `assets` key that do not exist in `assetByChunkName`
Fixes #176

fix handling of webpack stats files with non-js assets

---

poetry.lock

This should take care of capturing celery worker crashes

ref: Upgrade sentry sdk

---

tests/zeus/tasks/test_cleanup_builds.py
zeus/tasks/aggregate_job_stats.py
zeus/tasks/cleanup_builds.py

This will limit the effect of cleanup_builds (minor effect), and adjust the lock to have an expiration window the same as the task, as well as to fail immediately (to avoid blocking the worker).
bors r+

ref: Improve concurrency behavior in aggregate_build_stats

---

webapp/api.jsx

We patch XHR globally in the `send` method and we use it to determine if a request is finished or not.
If you call `send` before, and then hard overwrite `xhr.onreadystatechange` our SDK never picks up finished XHRs.
Examples here always call send after the callback is set
https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/send
and I think this is a misusage of the API.
Also, your callback would have just been invoked after the first call.
Talked to Kamil, not sure if we can work around this, maybe we can add a warning to the Integration to at least notify users that they did something wrong.

fix: Call xhr.send after setting up callback

---

zeus/vcs/backends/git.py

This is believed to be causing issues fetching known (valid) commits. Need to revisit doing cheaper repo clones.
bors r+

Remove depth usage in git

---

cloudbuild.yaml

Google has a maximum of 10 minutes. On to the next solution!
bors r+
This reverts commit 0c94004b134b20940e2b49cfbd0e42cd65df03f7.

Revert "ref: Extend build timeout to 20m"

---

zeus/tasks/resolve_ref.py

This resolves a race condition which was causing duplicate FailureReason's to end up in the database for unresolvable_ref. A follow up will be needed to cleanup the bad data and add an additional constraint.
bors r+

ref: Lock resolve_ref tasks to avoid duplicate failures

---

zeus/db/func.py

This was incorrectly building padding based on a single row.
Fixes ZEUS-1RPM
bors r+

fix: Correct padding on array aggregations

---

zeus/factories/failurereason.py
zeus/migrations/e373a7bffa18_unique_build_failures.py
zeus/models/failurereason.py

This adds a unique constraint on FailureReason(build_id, reason) WHERE job_id IS NULL.
bors r+

fix: Add constraint on build-specific failures

---

zeus/vcs/server.py

Some basic tests suggest this will add anywhere from 10mb to 90mb per process, but can save us a very large amount of processing time if there are a larger number of repositories causing evictions.

feat: Increase LRU cache size for revisions to 100k items

---

tests/zeus/api/resources/test_github_repositories.py
tests/zeus/api/resources/test_job_details.py
tests/zeus/api/resources/test_repository_details.py
tests/zeus/tasks/test_aggregate_job_stats.py
tests/zeus/tasks/test_deactivate_repo.py
zeus/api/resources/build_jobs.py
zeus/api/resources/change_request_details.py
zeus/api/resources/job_artifacts.py
zeus/api/resources/job_details.py
zeus/api/resources/repository_builds.py
zeus/api/resources/repository_change_requests.py
zeus/api/resources/repository_details.py
zeus/constants.py
zeus/providers/travis/webhook.py
zeus/tasks/aggregate_job_stats.py
zeus/tasks/cleanup_pending_artifacts.py
zeus/tasks/deactivate_repo.py
zeus/tasks/process_artifact.py
zeus/tasks/process_pending_artifact.py
zeus/tasks/process_travis_webhook.py
zeus/tasks/resolve_ref.py
zeus/tasks/send_build_notifications.py
zeus/tasks/sync_github_access.py
zeus/utils/celery.py
zeus/vcs/client.py
zeus/web/views/auth_github.py

This moves the `task.delay` abstraction into `zeus.config.celery`, ensuring
we can centrally control the behavior. Additionally it adds a `call` method
for doing the synchronous calls.
It also renames some tasks, which may result in lost jobs, but the important
ones should retry.
bors r+

ref: Add celery.delay abstraction to centralize task management

---

tests/zeus/api/resources/test_build_jobs.py
zeus/api/resources/build_jobs.py

This fixes a race condition between cleanup_jobs and newly enqueued jobs (which haven't started).
bors r+

fix: Set job.date_updated on every PUT
